### PR TITLE
Some more Codechef Problems solutions

### PR DESCRIPTION
**Pull request by rushabhshah309**
I've added some more Codechef solutions from September Cook-Off and Lunchtime.

### CODE REVIEW

**Review by yash982000 — COMMENTED** [review]
Codechef solutions from September Cook-Off and Lunchtime.

**Comment by yash982000** [comment]
Can you add solutions from October Challenge? 
LOL, ^_^

**Comment by rushabhshah309** [comment]
> Can you add solutions from October Challenge?
> LOL, ^_^

sure :P after it gets over.. :D

**Comment by yash982000** [comment]
Ofcourse, it was a joke. I don't want my repo to get banned 👍

**Pull request merged**
